### ISSUE TITLE
Readme Documentation incorrect

### ISSUE THREAD

**Issue by strangefreeworld** [Project-Mau/mau#4]
According to the documentation in your README, in order to instantiate an object in code, you just need to call `mau = Mau(target_format="html")`. When I attempted to do that, I get `TypeError: __init__() missing 1 required positional argument: 'config'
'. Digging through the code, I figured out that the call should be 'mau = Mau({}, "html")`. Your format looks interesting and I am playing around with it in a project I am working on.

**Comment by lgiordani** [comment]
Blimey! Thanks for opening the issue, I will fix this as soon as possible!

**Comment by lgiordani** [comment]
Hi! I resolved this in version 2.0.2, thanks for spotting it. I hope you'll find Mau useful!
